using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using PIM.Data;
using SHOP.Interfaces;
using SHOP.Models;
using SHOP.ViewModels;

namespace SHOP.Services;

public partial class CartService : ObservableObject, ICartService
    {
        private ProductsAPI productsAPI;
        // **** HERE is the reference to the actual Cart instance ****
        private readonly CartModel _currentCart;

        // Observable property for the count (which the ViewModel will use)
        [ObservableProperty]
        private int _itemCount;

        
        
        // Public property required by the interface
        // public int ItemCount => _itemCount; // Generated by ObservableProperty

        public CartService() // 
        {
            // Create the single instance of the Cart when the service is created
            
            _currentCart = new CartModel();
            productsAPI = ProductsAPI.GetProductAPI();

            //UpdateCount(); // Initial count
            
        }

        public async Task<Dictionary<ProductModel, int>> GetItemsList()
        {
            Dictionary<ProductModel, int> lPM = new Dictionary<ProductModel, int>();
            foreach(var key in _currentCart.Items.Keys)
            {
                var product = await productsAPI.GetProduct(key);
     
                lPM.Add(new ProductModel(product.sku, product.name,product.manufacturer,product.priceExclVAT, product.priceInclVAT, product.color,product.shortDesc, product.desc, product.size,
                    product.weight), _currentCart.Items[key]);
            }
            return lPM;
        }

        // Example method showing interaction with the _currentCart
        public void AddItem(ProductModel productModel, int quantity = 1)
        {
            // Find if an item already exists in the cart
            var existingItem = _currentCart.Items.FirstOrDefault(item => item.Key == productModel.SKU);

            if (existingItem.Value > 0)
            {
                _currentCart.Items[productModel.SKU] = existingItem.Value + quantity; 
            }
            else
            {
                // Add new item to the Cart instance's list
                _currentCart.Items.Add(productModel.SKU, quantity);
            }

            // ** Crucially, update the observable count property **
            UpdateCount();
        }

        public void RemoveItem(int productId)
        {
            var itemToRemove = _currentCart.Items.FirstOrDefault(item => item.Key == productId);
             if (itemToRemove.Value > 0)
             {
                 _currentCart.Items.Remove(itemToRemove.Key);
                 UpdateCount(); // Update the count
             }
        }
        
        public void ResetCart()
        {
            _currentCart.resetCart();
            UpdateCount();
        }
       

        // Method to update the observable property based on the Cart instance
        private void UpdateCount()
        {
            // Get the count FROM the Cart instance and update the service's property
            ItemCount = _currentCart.GetTotalUnitCount();
        }

        public async Task<float> getTotal()
        {
            float total = 0;
            foreach(var key in _currentCart.Items.Keys)
            {
                var product = await productsAPI.GetProduct(key);

                total += product.priceExclVAT * _currentCart.Items[key];
            }
            return total;
        }

         

       
    }

    